### ISSUE TITLE
DSC resources in "versioned" subfolders not working on VM's with older PS versions

### ISSUE THREAD

**Issue by csandfeld** [VirtualEngine/Lab#25]
I came to the conclusion that this does warrant it's own issue

Scenario:
Host OS is Windows 10.
Modules xComputerManagement, xNetworking etc. were installed with the Install-Module Cmdlet, causing the modules to have a folder structure including the modules version number.

As an example, the xComputerManagement module resides in the C:\Program Files\WindowsPowerShell\Modules\xComputerManagement\1.3.0 folder.

Now when I create a lab with Windows Server 2012R2 or Windows 8.1 VM’s, they get stuck in the bootstrap process, when trying to apply the DSC configuration. Reviewing the log shows that it cannot find the DSC resources.

Moving the modules out of the “version subfolder” fixes that. This makes sense since support for multiple versions of a module (and thus the “version subfolder”) is introduced with PowerShell 5.

It would be great if that could be taken into consideration, when resources are copied into VM disk.

**Comment by iainbrighton** [comment]
Yes - I have seen this issue, but only with the built-in Pester module on Win 10. i would need to do some testing but I think the logic could work like this:

* Rather than copying the entire \Modules directory, enumerate each sub directory
* Check for a .psd1 or .psm1 file
 * if present, copy that folder to the target VHDX
 * If not present, check each sub directory that has a number
  * Check for a .psd1 or .psm1 file and if present, copy that folder

Potential problems with this:
* This would loose the multiple module versions in the VHDX file.
* Depending on the order in which the directories are enumerated, we my hot have the latest version!

There are probably some other issues too. We might want to work on some code in a Gist to work this out?

**Comment by iainbrighton** [comment]
OK - here's a first pass: https://gist.github.com/iainbrighton/0daeabe4476494a91038.

Can you check whether this enumerates the correct DSC modules that need copying to the target VM?

This will hopefully only discover DSC resources, not all modules - assuming that's what we want?

**Comment by iainbrighton** [comment]
I think this is similar to problems raised by @SimonWahlin where the built-in WindowsFeature DSC resource (in the Windows\System32\WindowsPowerShell\Modules directory) is newer (v1.1.0) on the latest Win 10 build than is included in the WMF 4.0 build (v1.0.0)?

**Comment by csandfeld** [comment]
I'm surprised to see that the replies I sent by e-mail, did not make it into the issue threads. Did you see replies from me yesterday to this and other issues?

I have tested the code in the gist, and it does seem to return just the DSC resources (and the VirtualEngineLab module).

These are the modules returned ...
```PowerShell
C:\> GetDscResourceModule -Path "$env:ProgramFiles\WindowsPowerShell\Modules"

ModuleName          ModuleVersion Path                                                                
----------          ------------- ----                                                                
VirtualEngineLab    0.0           C:\Program Files\WindowsPowerShell\Modules\VirtualEngineLab         
xActiveDirectory    2.6.0.0       C:\Program Files\WindowsPowerShell\Modules\xActiveDirectory\2.6.0.0 
xComputerManagement 1.3.0         C:\Program Files\WindowsPowerShell\Modules\xComputerManagement\1.3.0
xDhcpServer         1.2           C:\Program Files\WindowsPowerShell\Modules\xDhcpServer\1.2          
xDnsServer          1.1           C:\Program Files\WindowsPowerShell\Modules\xDnsServer\1.1           
xNetworking         2.3.0.0       C:\Program Files\WindowsPowerShell\Modules\xNetworking\2.3.0.0      
xSmbShare           1.1.0.0       C:\Program Files\WindowsPowerShell\Modules\xSmbShare\1.1.0.0        
```

Out of this list of modules available in the folder (another good job on the GitHubRepository module btw.) ...
```PowerShell
C:\> Get-ChildItem -Path "$env:ProgramFiles\WindowsPowerShell\Modules" | Select-Object -Property FullName

FullName                                                      
--------                                                      
C:\Program Files\WindowsPowerShell\Modules\GitHubRepository   
C:\Program Files\WindowsPowerShell\Modules\PackageManagement  
C:\Program Files\WindowsPowerShell\Modules\Pester             
C:\Program Files\WindowsPowerShell\Modules\PowerShellGet      
C:\Program Files\WindowsPowerShell\Modules\PSReadline         
C:\Program Files\WindowsPowerShell\Modules\PSScriptAnalyzer   
C:\Program Files\WindowsPowerShell\Modules\VirtualEngineLab   
C:\Program Files\WindowsPowerShell\Modules\xActiveDirectory   
C:\Program Files\WindowsPowerShell\Modules\xComputerManagement
C:\Program Files\WindowsPowerShell\Modules\xDhcpServer        
C:\Program Files\WindowsPowerShell\Modules\xDnsServer         
C:\Program Files\WindowsPowerShell\Modules\xNetworking        
C:\Program Files\WindowsPowerShell\Modules\xSmbShare          
```

I also tested having multiple versions of a module (actually just copied a module and gave it another version number), and it consistently returned the highest version number.

**Comment by csandfeld** [comment]
I don't know what @SimonWahlin have reported, so can't say if this is similar. What I can say though, is that I experienced the same problem when running on a 2016TP3 host.

**Comment by iainbrighton** [comment]
No - not seen any comments coming back other than what you see here :(

Glad you find the GitHubRepository module useful! I got fed up of downloading development branch ZIP files. If you haven't seen it, it is also published to the PowerShell Gallery (as the lab resource will be once I've closed out the open issues).

I'll open a new issue with @SimonWhalin 's issue which is similar..

**Comment by csandfeld** [comment]
Bugger ... guess I'll have to go trawling in my sent items

**Comment by csandfeld** [comment]
Reply to your first post (from my sent items):

Yes, I will be happy to assist any way I can. I had some thoughts as well about trying to determine the PowerShell version in the VHDX, and keeping the version folders if supported on the target. Just not sure how to do that at this point.

**Comment by iainbrighton** [comment]
@csandfeld version 0.8.7 should resolve this issue. I've tested the following:
* Using a Windows 10 host
* Installed DSC resources from the PowerShell Gallery with Install-Module
* Created a 2012R2 VM
* Logged on to 2012R2 VM
* Ran `Get-DscResource` and the resources were listed/returned

Let me know if it does or doesn't work! Thx.

**Comment by csandfeld** [comment]
Brilliant ... I will check it out and let you know

**Comment by csandfeld** [comment]
I'm afraid there is still an issue here.
Ran into the following problem when testing the password/credential fix for #16.

* Using a Windows 10 host (PSVersion: 5.0.10240.16384)
  * DSC Resource modules installed using Install-Module
  * Modules resisde in "versioned" subfolders (e.g. Modules\xNetworking\2.3.0.0
* Created a Windows Server 2016 TP4 VM
  * VM was stuck in a never ending loop trying to bootstrap
  * Reset the VM and ran bootstrap.ps1 manually
  * Got errors that the MSFT_xFirewall does not exist

Imagine my surprise when this was what I found as I looked at the installed modules (the xNetworking resource is in the 2.3.0.0 folder):

```PowerShell
PS C:\> gci 'C:\Program Files\WindowsPowerShell\Modules\'

    Directory: C:\Program Files\WindowsPowerShell\Modules

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       26-11-2015     18:28                1.1
d-----       26-11-2015     18:28                1.1.0.0
d-----       26-11-2015     18:28                1.2
d-----       26-11-2015     18:28                1.3.0
d-----       26-11-2015     18:28                2.3.0.0
d-----       26-11-2015     18:28                2.6.0.0
d---s-       30-10-2015     08:22                PackageManagement
d---s-       30-10-2015     08:22                Pester
d---s-       30-10-2015     08:22                PowerShellGet
d-----       30-10-2015     08:22                PSReadline
```

**Comment by csandfeld** [comment]
Og by the way ... just to clarify - the above was with the "Issue 16" branch.

**Comment by csandfeld** [comment]
Just verified the same behaviour with the latest code from the dev branch

**Comment by iainbrighton** [comment]
Ah - I think I know exactly what this is. I didn't write a Pester test "as it's only one copy-item line of code..." That'll teach me :(

Will fix tomorrow! Thx for testing.

**Comment by iainbrighton** [comment]
@csandfeld this should be resolved in the latest dev branch 0.8.9. I've merged the -Credential/-Password functionality into dev.

**Comment by csandfeld** [comment]
Seem to work fine in the latest dev version.
Good job :+1:
